server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.83.5:3306/code07?serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: 123456
  #    password: XXX
  jpa:
    hibernate:
      ddl-auto: update  #自动更新表
    show-sql: true
  thymeleaf:
    cache: false

userImageFilePath: /home/code07/userImage/

articleImageFilePath: /home/code07/uploadImage/

lucenePath: /home/code07/myLucene

quartzname: test
quartzpath: com.linka39.code07.quartzJob.
